defaults:
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

input: /Users/mona/Library/CloudStorage/GoogleDrive-xinqili16@g.ucla.edu/My Drive/Data/Registration/patient_registration_LiTing_Mona/019
label: CE9

type: single_exp
threshold: 2000
base_actime: 34000
FOV: 128
rounds: 3

clean: True
verbose: True